module.exports = [{
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "previousAdmin",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "address",
		"name": "newAdmin",
		"type": "address"
	}],
	"name": "AdminChanged",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "beacon",
		"type": "address"
	}],
	"name": "BeaconUpgraded",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "owner",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "price",
		"type": "uint256"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "timestamps",
		"type": "uint256"
	}],
	"name": "DoneOnShelf",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "from",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "address",
		"name": "to",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "price",
		"type": "uint256"
	}],
	"name": "DonePurchase",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "to",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "amount",
		"type": "uint256"
	}],
	"name": "DoneWithdraw",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "bytes32",
		"name": "role",
		"type": "bytes32"
	}, {
		"indexed": true,
		"internalType": "bytes32",
		"name": "previousAdminRole",
		"type": "bytes32"
	}, {
		"indexed": true,
		"internalType": "bytes32",
		"name": "newAdminRole",
		"type": "bytes32"
	}],
	"name": "RoleAdminChanged",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "bytes32",
		"name": "role",
		"type": "bytes32"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "account",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "sender",
		"type": "address"
	}],
	"name": "RoleGranted",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "bytes32",
		"name": "role",
		"type": "bytes32"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "account",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "sender",
		"type": "address"
	}],
	"name": "RoleRevoked",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "implementation",
		"type": "address"
	}],
	"name": "Upgraded",
	"type": "event"
}, {
	"inputs": [],
	"name": "DEFAULT_ADMIN_ROLE",
	"outputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "EXADMIN_ROLE",
	"outputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "UPGRADER_ROLE",
	"outputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "WITHDRAW_ROLE",
	"outputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "buy",
	"outputs": [],
	"stateMutability": "payable",
	"type": "function"
}, {
	"inputs": [],
	"name": "getMaxDuration",
	"outputs": [{
		"internalType": "uint256",
		"name": "duration",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "getMinDuration",
	"outputs": [{
		"internalType": "uint256",
		"name": "duration",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "getNftCode",
	"outputs": [{
		"internalType": "contract IERC721",
		"name": "nftCode",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "getOffShelfTime",
	"outputs": [{
		"internalType": "uint256",
		"name": "offShelfTime",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}],
	"name": "getPrices",
	"outputs": [{
		"internalType": "uint256",
		"name": "price",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes32",
		"name": "role",
		"type": "bytes32"
	}],
	"name": "getRoleAdmin",
	"outputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "getVersion",
	"outputs": [{
		"internalType": "uint256",
		"name": "version",
		"type": "uint256"
	}],
	"stateMutability": "pure",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes32",
		"name": "role",
		"type": "bytes32"
	}, {
		"internalType": "address",
		"name": "account",
		"type": "address"
	}],
	"name": "grantRole",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes32",
		"name": "role",
		"type": "bytes32"
	}, {
		"internalType": "address",
		"name": "account",
		"type": "address"
	}],
	"name": "hasRole",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "contract IERC721",
		"name": "nftCode",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "minDuration",
		"type": "uint256"
	}, {
		"internalType": "uint256",
		"name": "maxDuration",
		"type": "uint256"
	}],
	"name": "initialize",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [],
	"name": "proxiableUUID",
	"outputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes32",
		"name": "role",
		"type": "bytes32"
	}, {
		"internalType": "address",
		"name": "account",
		"type": "address"
	}],
	"name": "renounceRole",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes32",
		"name": "role",
		"type": "bytes32"
	}, {
		"internalType": "address",
		"name": "account",
		"type": "address"
	}],
	"name": "revokeRole",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"internalType": "uint256",
		"name": "price",
		"type": "uint256"
	}, {
		"internalType": "uint256",
		"name": "offShelfTime",
		"type": "uint256"
	}],
	"name": "sell",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "duration",
		"type": "uint256"
	}],
	"name": "setMaxDuration",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "duration",
		"type": "uint256"
	}],
	"name": "setMinDuration",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "contract IERC721",
		"name": "nftCode",
		"type": "address"
	}],
	"name": "setNftCode",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes4",
		"name": "interfaceId",
		"type": "bytes4"
	}],
	"name": "supportsInterface",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "newImplementation",
		"type": "address"
	}],
	"name": "upgradeTo",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "newImplementation",
		"type": "address"
	}, {
		"internalType": "bytes",
		"name": "data",
		"type": "bytes"
	}],
	"name": "upgradeToAndCall",
	"outputs": [],
	"stateMutability": "payable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "to",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "amount",
		"type": "uint256"
	}],
	"name": "withdraw",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}]
